#!/usr/bin/env bash
# this script configures a new ubuntu machine:
# update packages, install nginx,set it to listen to port 80
# Serve a page that would return a Hello World string
sudo apt-get update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-ubuntu.html
#start nginx
sudo service nginx start
