#!/usr/bin/env bash
#this script configures a new ubuntu machine:
#
# WILL ADD MORE CMMENTS LATER, HAVING SOME CONNECTIVITY ISSUES`AFTER SUFFERING
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
