#!/usr/bin/env bash
# script that configure an Nginx server redirect_me

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "47s/.*/\tlocation \/redirect_me {\n\t\treturn 301 http:\/\/github.com\/\;\n\t}/" /etc/nginx/sites-available/default
sudo service nginx restart
