#!/usr/bin/env bash
# update package list
sudo apt -y update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
# Restart nginx
sudo service nginx restart
