#!/usr/bin/env bash
# This is script displays "To infinity and beyond" indefinitely
# Include sleep 2 in between each iteration
# It displays "I am invincible...." receiving a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I am invincible!!!"' SIGTERM
done
