#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
# Displays hours from 0 to 12
# Displays minutes from 1 to 59
# Must use the while loop

thour=0

while [ $thour -le 12 ]
do
	echo "Hour: $thour"

	tminute=1
	while [ $tminute -le 59 ]
	do
		echo "$tminute"
		((tminute++))
	done
	((thour++))
done
