#!/usr/bin/env bash
# This script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu

server="35.174.200.179"

# Define the private key file path
private_key="~/.ssh/school"

# Define the username
username="ubuntu"

# SSH command, -i flag specifies the identity (private key) file to be used for authentication
ssh -i "$private_key" "$username@$server"
